# Generated by Django 5.0.6 on 2024-07-22 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyIDSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='SubUserIDSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('linkedin_url', models.URLField(null=True)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=150)),
                ('user_type', models.CharField(default='admin', max_length=12)),
                ('company_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserIDSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('date_of_incorporation', models.DateField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('website_url', models.URLField(null=True)),
                ('linkedin_url', models.URLField(null=True)),
                ('subscription_type', models.CharField(max_length=20, null=True)),
                ('company_type', models.CharField(max_length=10, null=True)),
                ('location', models.CharField(max_length=20, null=True)),
                ('business_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.businesstype')),
                ('sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.sector')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='app1.user')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('logo', models.ImageField(null=True, upload_to='clients_logo')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='app1.company')),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='app1.company')),
            ],
        ),
        migrations.CreateModel(
            name='CapTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('linkedin_url', models.URLField()),
                ('photo', models.ImageField(null=True, upload_to='photos')),
                ('percentage_of_shares', models.DecimalField(decimal_places=2, max_digits=5)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cap_tables', to='app1.company')),
            ],
        ),
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=15)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisors', to='app1.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tam', models.FloatField()),
                ('cagr', models.FloatField()),
                ('number_of_clients_users', models.IntegerField()),
                ('previous_year_revenue', models.FloatField()),
                ('current_year_revenue_arr', models.FloatField()),
                ('current_monthly_burn_rate', models.FloatField()),
                ('forecasted_revenue_for_next_year', models.FloatField()),
                ('equity_funds_raised_so_far', models.FloatField()),
                ('funds_needed', models.FloatField()),
                ('business_plan', models.FileField(null=True, upload_to='business_plan')),
                ('pitch_and_product', models.FileField(null=True, upload_to='pitch_and_product')),
                ('business_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.businessstage')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_profiles', to='app1.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='app1.company')),
            ],
        ),
        migrations.CreateModel(
            name='ExecutiveMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('designation', models.CharField(max_length=100)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executive_members', to='app1.company')),
            ],
        ),
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('linkedin_url', models.URLField()),
                ('short_profile', models.TextField(null=True)),
                ('photo', models.ImageField(null=True, upload_to='photos')),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='founders', to='app1.company')),
            ],
        ),
        migrations.CreateModel(
            name='HeterogenousProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('expected_revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expected_growth_rate', models.IntegerField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
        migrations.CreateModel(
            name='HomogenousProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('selling_price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('units_sold', models.IntegerField()),
                ('expected_growth_rate', models.IntegerField()),
                ('revenue_from_product', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('cost_of_revenue', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('gross_profit', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('operating_expense', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('operating_income', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('net_non_operating_interest_income_expense', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('other_income_expense', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('pretax_income', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('tax_provision', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('net_income_common_stockholders', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('diluted_ni_available_to_com_stockholders', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('basic_eps', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('diluted_eps', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('basic_average_shares', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('diluted_average_shares', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_operating_income_as_reported', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_expenses', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('net_income_from_continuing_and_discontinued_operation', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('normalized_income', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('interest_income', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('interest_expense', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('net_interest_income', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('ebit', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('ebitda', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('reconciled_cost_of_revenue', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('reconciled_depreciation', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('net_income_from_continuing_operation_net_minority_interest', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_unusual_items_excluding_goodwill', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_unusual_items', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('normalized_ebitda', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('tax_rate_for_calcs', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('tax_effect_of_unusual_items', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('creator_id', models.CharField(max_length=12, null=True)),
                ('modifier_id', models.CharField(max_length=12, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_urls', to='app1.company')),
            ],
        ),
        migrations.CreateModel(
            name='SolvedProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solved_problems', to='app1.company')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('subuser_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('creator_id', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('linkedin_url', models.URLField(null=True)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=10)),
                ('user_type', models.CharField(max_length=12)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
    ]
