# Generated by Django 5.0.6 on 2024-07-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomestatement',
            name='monthly_or_quarterly_or_yearly',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
