# Generated by Django 5.0.6 on 2024-07-24 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_incomestatement_monthly_or_quarterly_or_yearly'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incomestatement',
            old_name='basic_average_shares',
            new_name='depreciation_and_amortization',
        ),
        migrations.RenameField(
            model_name='incomestatement',
            old_name='diluted_average_shares',
            new_name='equity_share_dividends',
        ),
        migrations.RenameField(
            model_name='incomestatement',
            old_name='diluted_ni_available_to_com_stockholders',
            new_name='gain_or_loss_on_sale_of_security',
        ),
        migrations.RenameField(
            model_name='incomestatement',
            old_name='ebit',
            new_name='general_and_administrative_expenses',
        ),
        migrations.RenameField(
            model_name='incomestatement',
            old_name='interest_income',
            new_name='interest_expense_non_operating',
        ),
        migrations.RenameField(
            model_name='incomestatement',
            old_name='interest_expense',
            new_name='interest_income_non_operating',
        ),
        migrations.RenameField(
            model_name='incomestatement',
            old_name='net_income_common_stockholders',
            new_name='net_income',
        ),
        migrations.RenameField(
            model_name='incomestatement',
            old_name='net_income_from_continuing_and_discontinued_operation',
            new_name='net_income_to_common_stockholders',
        ),
        migrations.RenameField(
            model_name='incomestatement',
            old_name='net_income_from_continuing_operation_net_minority_interest',
            new_name='operating_revenue',
        ),
        migrations.RenameField(
            model_name='incomestatement',
            old_name='net_interest_income',
            new_name='other_income_or_expense',
        ),
        migrations.RenameField(
            model_name='incomestatement',
            old_name='normalized_ebitda',
            new_name='other_non_operating_income_or_expenses',
        ),
        migrations.RenameField(
            model_name='incomestatement',
            old_name='normalized_income',
            new_name='preference_share_dividends',
        ),
        migrations.RenameField(
            model_name='incomestatement',
            old_name='other_income_expense',
            new_name='research_and_development_expense',
        ),
        migrations.RenameField(
            model_name='incomestatement',
            old_name='reconciled_cost_of_revenue',
            new_name='retained_earnings',
        ),
        migrations.RenameField(
            model_name='incomestatement',
            old_name='reconciled_depreciation',
            new_name='selling_and_marketing_expense',
        ),
        migrations.RenameField(
            model_name='incomestatement',
            old_name='tax_effect_of_unusual_items',
            new_name='selling_general_and_administrative_expense',
        ),
        migrations.RenameField(
            model_name='incomestatement',
            old_name='tax_rate_for_calcs',
            new_name='special_income_or_charges',
        ),
        migrations.RenameField(
            model_name='incomestatement',
            old_name='total_expenses',
            new_name='write_off',
        ),
        migrations.RemoveField(
            model_name='incomestatement',
            name='total_operating_income_as_reported',
        ),
        migrations.RemoveField(
            model_name='incomestatement',
            name='total_unusual_items',
        ),
        migrations.RemoveField(
            model_name='incomestatement',
            name='total_unusual_items_excluding_goodwill',
        ),
    ]
